jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set environment variables
        run: echo "VITE_BASE_URL=/$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build with Next.js
        run: bun run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
